go.mod
go.sum
pkg/adapter/openai/interface.go
pkg/adapter/openai/openai.go
pkg/constant/constant.go
pkg/discord/command/brainery/base.go
pkg/discord/command/brainery/brainery.go
pkg/discord/command/brainery/interface.go
pkg/discord/command/command.go
pkg/discord/listener.go
pkg/discord/service/brainery/brainery.go
pkg/discord/service/brainery/interface.go
pkg/discord/service/interface.go
pkg/discord/service/service.go
pkg/discord/view/base/embed.go
pkg/discord/view/brainery/brainery.go
pkg/discord/view/brainery/interface.go
pkg/discord/view/errors/custom_error.go
pkg/discord/view/errors/interface.go
pkg/discord/view/interface.go
pkg/discord/view/view.go
pkg/model/brainery.go

// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

feat: brainery post article command

---

pkg/adapter/fortress/fortress.go
pkg/adapter/fortress/interface.go
pkg/discord/command/icy/icy.go
pkg/discord/service/icy/icy.go
pkg/discord/service/icy/interface.go
pkg/discord/view/icy/accounting.go
pkg/discord/view/icy/info.go
pkg/discord/view/icy/interface.go
pkg/model/icy.go

feat: icy accounting - add total 30days reward

---

pkg/discord/command/event/event.go
pkg/discord/view/event/schedule_event.go
pkg/model/discord_event.go
pkg/model/event.go

Update response layout for command list event
Before 
After

fix: list event cmd resp layout

---

pkg/adapter/fortress/interface.go
pkg/adapter/fortress/memo.go
pkg/discord/command/memo/base.go
pkg/discord/command/memo/interface.go
pkg/discord/command/memo/memo.go
pkg/discord/service/memo/interface.go
pkg/discord/service/memo/memo.go
pkg/discord/view/memo/interface.go
pkg/discord/view/memo/list.go

Update command get list memo logs to support filter by time period

fix: cmd list memo with time period

---

pkg/discord/command/memo/memo.go
pkg/discord/view/memo/list.go
pkg/model/memos.go

fix: update memo cmd layout - GROUP BY CATEGORY

fix: update memo cmd layout

---

pkg/discord/view/memo/list.go

Just only grouped by whitelisted categories.

fix: update memo list layout

---

pkg/discord/view/help/help.go

Update help msg content. Hide all except earn, event and profile

fix: update help msg content

---

pkg/discord/view/event/event.go
pkg/discord/view/memo/list.go

Update help cmd layout
Update memo list: add earn category

fix: update msg layout of event help and memo cmd

---

pkg/adapter/fortress/interface.go
pkg/adapter/fortress/memo.go
pkg/discord/command/memo/base.go
pkg/discord/command/memo/memo.go
pkg/discord/service/memo/interface.go
pkg/discord/service/memo/memo.go
pkg/discord/view/memo/interface.go
pkg/discord/view/memo/list.go
pkg/model/memos.go
pkg/utils/stringutils/strings.go

feat: add memo list pr view

---

pkg/adapter/fortress/fortress.go
pkg/adapter/fortress/interface.go
pkg/discord/command/earn/earn.go
pkg/discord/service/earn/earn.go
pkg/discord/service/earn/interface.go
pkg/discord/view/earn/interface.go
pkg/discord/view/earn/list.go
pkg/model/earn.go

- Point cmd `?earn list` to new handler that is fetch list earn from memo instead of notion.
- Change this cmd layout

feat: update cmd earn list to get data from memo

---

pkg/adapter/fortress/discord.go
pkg/adapter/fortress/interface.go
pkg/config/config.go
pkg/discord/command/command.go
pkg/discord/command/topic/base.go
pkg/discord/command/topic/interface.go
pkg/discord/command/topic/topic.go
pkg/discord/interaction_listener.go
pkg/discord/service/interface.go
pkg/discord/service/researchtopic/interface.go
pkg/discord/service/researchtopic/research_topic.go
pkg/discord/service/service.go
pkg/discord/view/base/embed.go
pkg/discord/view/interface.go
pkg/discord/view/topic/inteface.go
pkg/discord/view/topic/list.go
pkg/discord/view/topic/topic.go
pkg/discord/view/view.go
pkg/model/research_topic.go

- without pagination
- with pagination

feat: add topic command

---

go.mod

fix: upgrade go mod version

---

Dockerfile

// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

fix: update docker to go v1.20

---

pkg/adapter/fortress/fortress.go
pkg/adapter/fortress/interface.go
pkg/discord/command/command.go
pkg/discord/command/memo/memo.go
pkg/discord/command/ogif/base.go
pkg/discord/command/ogif/interface.go
pkg/discord/command/ogif/news.go
pkg/discord/command/ogif/ogif.go
pkg/discord/service/event/discord.go
pkg/discord/service/event/interface.go
pkg/discord/view/interface.go
pkg/discord/view/ogif/help.go
pkg/discord/view/ogif/interface.go
pkg/discord/view/ogif/ogif.go
pkg/discord/view/ogif/stats.go
pkg/discord/view/view.go
pkg/model/ogif.go
pkg/utils/stringutils/strings.go

feat: cmd ogif

---

pkg/adapter/fortress/interface.go
pkg/adapter/fortress/memo.go
pkg/discord/command/memo/base.go
pkg/discord/command/memo/memo.go
pkg/discord/service/memo/interface.go
pkg/discord/service/memo/memo.go
pkg/discord/view/memo/interface.go
pkg/discord/view/memo/memo.go

feat: update cmd ?memo top

---

.env.example
pkg/adapter/adapter.go
pkg/adapter/interface.go
pkg/adapter/n8n/interface.go
pkg/adapter/n8n/n8n.go
pkg/config/config.go
pkg/discord/command/ai/ai.go
pkg/discord/command/command.go
pkg/discord/command/df/base.go
pkg/discord/command/df/df.go
pkg/discord/command/df/interface.go
pkg/discord/listener.go
pkg/discord/service/ai/ai.go
pkg/discord/service/ai/interface.go
pkg/discord/view/df/df.go
pkg/discord/view/df/help.go
pkg/discord/view/df/interface.go
pkg/discord/view/interface.go
pkg/discord/view/view.go
pkg/utils/permutil/permission.go

- Add `N8N_WEBHOOK_URL` to `.env`

feat: forward ?ai prompt to n8n

---

.env.example
pkg/adapter/adapter.go
pkg/adapter/n8n/n8n.go
pkg/config/config.go

chore: handle basic auth for n8n webhook

---

pkg/discord/command/df/df.go

chore: trim df command prefix

---

pkg/adapter/n8n/interface.go
pkg/adapter/n8n/n8n.go
pkg/discord/command/df/df.go
pkg/discord/service/ai/ai.go
pkg/discord/service/ai/interface.go
pkg/discord/view/df/df.go
pkg/discord/view/df/interface.go
pkg/model/ai.go

chore: handle formatted response from n8n webhook

---

pkg/adapter/n8n/interface.go
pkg/adapter/n8n/n8n.go
pkg/discord/command/command.go
pkg/discord/command/df/df.go
pkg/discord/service/ai/ai.go
pkg/discord/service/ai/interface.go
pkg/discord/service/profile/get.go

```
"body": 
{
"author_id": "861984704084181012",
"author_name": "huymaius",
"author_role_id": "1098469407329632276",
"content": "what latest invoice of yolo lab"
}
```

fix: get highest role

---

pkg/discord/listener.go
pkg/discord/view/base/embed.go
pkg/discord/view/df/df.go
pkg/model/discord_message.go

fix: reply message

---

pkg/discord/command/advance/base.go
pkg/discord/view/errors/command_disabled.go
pkg/discord/view/errors/interface.go
pkg/discord/view/salary/list.go

- Temporary return command not found to disable the salary command.

refactor: simplify command execution logic in Salary struct
